# Generated by Django 3.0 on 2019-12-11 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_rest_passwordreset', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mmiimi',
        ),
    ]
