# Generated by Django 3.0 on 2020-06-20 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='normalpost',
            name='basepost_ptr',
        ),
        migrations.RemoveField(
            model_name='normalpost',
            name='user',
        ),
        migrations.DeleteModel(
            name='BasePost',
        ),
        migrations.DeleteModel(
            name='NormalPost',
        ),
    ]
