# Generated by Django 3.0 on 2020-09-18 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200918_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='group_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='posts.GroupPost'),
        ),
        migrations.AlterField(
            model_name='like',
            name='normal_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='posts.FeedPost'),
        ),
    ]
