# Generated by Django 3.0 on 2020-09-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200918_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='feedpost',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='grouppost',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
