# Generated by Django 3.0 on 2020-09-18 14:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_auto_20200918_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='normal_post',
            new_name='feed_post',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='normal_post',
            new_name='feed_post',
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('user', 'feed_post')},
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'feed_post')},
        ),
    ]
