# Generated by Django 3.0 on 2020-09-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200918_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='create_post',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='share_post',
        ),
        migrations.AddField(
            model_name='activity',
            name='post_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_type',
            field=models.CharField(blank=True, choices=[('feed_post', 'feed_post'), ('group_post', 'group_post')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='like',
            name='like_type',
            field=models.CharField(blank=True, choices=[('feed_post', 'feed_post'), ('group_post', 'group_post')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('like_feed_post', 'like_feed_post'), ('comment_feed_post', 'comment_feed_post'), ('create_feed_post', 'create_feed_post'), ('share_feed_post', 'share_feed_post')], max_length=50, null=True),
        ),
    ]
