# Generated by Django 3.0 on 2020-09-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200906_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedpost',
            name='visibilty_status',
            field=models.CharField(blank=True, choices=[('connections', 'connections'), ('everyone', 'everyone'), ('connection_and_followers', 'connection_and_followers')], max_length=50, null=True),
        ),
    ]
