# Generated by Django 3.0 on 2020-09-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20200918_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='post_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('like_post', 'like_post'), ('comment_post', 'comment_post'), ('share_post', 'share_post'), ('create_post', 'create_post')], max_length=50, null=True),
        ),
    ]
