# Generated by Django 3.0 on 2020-09-06 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_feedpost_visibilty_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='post',
        ),
        migrations.AddField(
            model_name='activity',
            name='create_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_post_activity', to='posts.FeedPost'),
        ),
        migrations.AddField(
            model_name='activity',
            name='share_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='share_post_activity', to='posts.FeedPost'),
        ),
    ]
