# Generated by Django 3.0 on 2020-09-06 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20200906_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='create_post',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='share_post',
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('like', 'like'), ('comment', 'comment'), ('create_post', 'create_post'), ('share_post', 'share_post')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.FeedPost'),
        ),
    ]
