# Generated by Django 3.0 on 2020-09-20 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20200920_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='post_id',
        ),
        migrations.AddField(
            model_name='activity',
            name='feed_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='posts.FeedPost'),
        ),
        migrations.AddField(
            model_name='activity',
            name='group_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='posts.GroupPost'),
        ),
    ]
