# Generated by Django 2.2 on 2020-05-21 19:16

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test2User',
            fields=[
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
            ],
        ),
        migrations.CreateModel(
            name='Sachin',
            fields=[
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
            ],
        ),
    ]
