# Generated by Django 3.0 on 2020-06-18 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='authy_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verfied',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_verfied',
        ),
    ]
