# Generated by Django 3.0 on 2020-09-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200919_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_cover_photo_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_profile_photo_present',
            field=models.BooleanField(default=False),
        ),
    ]
