# Generated by Django 3.0 on 2020-06-20 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200620_2146'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConnectionRequest',
            new_name='Connection',
        ),
    ]
