# Generated by Django 3.0 on 2020-08-19 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200620_2148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connection',
            options={'verbose_name': 'Connection', 'verbose_name_plural': 'Connections'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='image/thumbnail/', verbose_name='thumbnail'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='connection',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='connection',
            unique_together={('sender', 'receiver')},
        ),
        migrations.RemoveField(
            model_name='connection',
            name='accepted',
        ),
        migrations.CreateModel(
            name='FriendshipRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('rejected', models.DateTimeField(blank=True, null=True)),
                ('viewed', models.DateTimeField(blank=True, null=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_requests_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Friendship Request',
                'verbose_name_plural': 'Friendship Requests',
                'unique_together': {('from_user', 'to_user')},
            },
        ),
    ]
