# Generated by Django 3.0 on 2020-08-19 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200819_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='thumbnail',
            field=models.FileField(blank=True, default='image/thumnail/Desert.jpg', null=True, upload_to='image/thumbnail/', verbose_name='thumbnail'),
        ),
    ]
