# Generated by Django 3.0 on 2020-08-19 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200819_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='thumbnail',
            field=models.FileField(blank=True, default='image/thumbnail/Desert.jpg', null=True, upload_to='image/thumbnail/', verbose_name='thumbnail'),
        ),
    ]
