# Generated by Django 3.0 on 2020-08-19 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200819_0951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection',
            old_name='sender',
            new_name='from_user',
        ),
        migrations.RenameField(
            model_name='connection',
            old_name='receiver',
            new_name='to_user',
        ),
        migrations.AlterUniqueTogether(
            name='connection',
            unique_together={('from_user', 'to_user')},
        ),
    ]
