# Generated by Django 3.0 on 2020-09-06 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20200819_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='complete_status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cover_photo',
            field=models.FileField(blank=True, default='/image/cover_photo/default.png', null=True, upload_to='image/cover_photo/', verbose_name='cover_photo'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_city',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='no_of_followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='no_of_following',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='no_of_friend',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_photo',
            field=models.FileField(blank=True, default='/image/profile_photo/default.png', null=True, upload_to='image/profile_photo/', verbose_name='profile_photo'),
        ),
        migrations.CreateModel(
            name='VisibilitySettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('who_can_see_your_likes_and_comments', models.CharField(choices=[('connections', 'connections'), ('everyone', 'everyone'), ('myself', 'myself'), ('connection_and_followers', 'connection_and_followers')], default='everyone', max_length=50)),
                ('who_can_see_connection_list', models.CharField(choices=[('connections', 'connections'), ('everyone', 'everyone'), ('myself', 'myself'), ('connection_and_followers', 'connection_and_followers')], default='everyone', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visibility_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
