# Generated by Django 3.0 on 2020-09-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20200906_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cover_photo',
            field=models.FileField(blank=True, null=True, upload_to='image/cover_photo/', verbose_name='cover_photo'),
        ),
    ]
